---
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: "angular"
    releaseRules:
    - type: "refactor"
      release: patch
    parserOpts:
      noteKeywords:
      - BREAKING CHANGE
      - BREAKING CHANGES
- "@semantic-release/release-notes-generator"
- "@semantic-release/gitlab"
# - - "@semantic-release/exec"
#   - successCmd: |-
#       cat << EOF >> version.env
#       GIT_TAG=${nextRelease.gitTag}
#       LAST_VERSION=${lastRelease.version}
#       EOF
branches:
- develop
