apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cachedstate
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ include "snowflake-id.fullname" . }}-redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: {{ include "snowflake-id.fullname" . }}-redis
      key:  redis-password
auth:
  secretStore: kubernetes