apiVersion: v1
kind: Service
metadata:
  name: {{ include "snowflake-id.webhookService" . }}
  labels:
    {{- include "snowflake-id.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.webhook.port }}
      targetPort: 8443
      protocol: TCP
      name: https
    - port: {{ .Values.service.health.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "snowflake-id.selectorLabels" . | nindent 4 }}
