apiVersion: v2
appVersion: v1.1.0
description: A Helm chart for Kubernetes
name: snowflake-id-chart
type: application 
version: v1.0.3
dependencies:
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 16.5.0