name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/snowflake-id
      context: .
      dockerfile: ./Dockerfile
    secrets: inherit
  deploy-dev:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/snowflake-id
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: guardian
      releaseName: snowflake-id
      revision: main
      dir: deploy/dev
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
#  deploy-prod:
#    if: github.ref == 'refs/heads/main'
#    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
#    needs:
#      - build
#    with:
#      images: followis/follow-server
#      tag: sha-${{ github.sha }}
#      cluster: prod
#      namespace: follow
#      releaseName: follow-server
#      revision: main
#      dir: deploy/prod
#    secrets:
#      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
